name: release-please

on:
  push:
    branches:
      - master

jobs:
  release_please:

    runs-on: ubuntu-slim

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}

    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0
        id: release
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
