name: release-please

on:
  push:
    branches:
      - master

jobs:
  release_please:

    runs-on: ubuntu-latest

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}

    steps:
      - uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4.4.1
        id: release
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
