name: release-please

on:
  push:
    branches:
      - master

jobs:
  release_please:

    runs-on: ubuntu-latest

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}

    steps:
      - uses: googleapis/release-please-action@c2a5a2bd6a758a0937f1ddb1e8950609867ed15c # v4.3.0
        id: release
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
