name: release-please

on:
  push:
    branches:
      - master

jobs:
  release_please:

    runs-on: ubuntu-latest

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}

    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
